In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [2]:
df.iloc[0:10]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
7,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49,False,False,Romania,NaN,NaN,NaN,Zitec,"['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...","{'cloud': ['gcp', 'azure', 'aws', 'bigquery', ..."
8,Business Analyst,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34,False,False,Denmark,NaN,NaN,NaN,Hempel,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

In [3]:
df.loc[0:10, 'salary_rate':'salary_hour_avg']

   salary_rate  salary_year_avg  salary_hour_avg
0          NaN              NaN              NaN
1          NaN              NaN              NaN
2          NaN              NaN              NaN
3          NaN              NaN              NaN
4          NaN              NaN              NaN
5          NaN              NaN              NaN
6          NaN              NaN              NaN
7          NaN              NaN              NaN
8          NaN              NaN              NaN
9          NaN              NaN              NaN
10         NaN              NaN              NaN

Data cleaning

In [6]:
median_salary_year = df['salary_year_avg'].median()

In [7]:
median_salary_hour = df['salary_hour_avg'].median()

In [15]:
df_filled = df
df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(median_salary_year)

In [16]:
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(median_salary_hour)

In [17]:
df_filled.loc[0:10, 'salary_rate':'salary_hour_avg']

   salary_rate  salary_year_avg  salary_hour_avg
0          NaN         115000.0            45.98
1          NaN         115000.0            45.98
2          NaN         115000.0            45.98
3          NaN         115000.0            45.98
4          NaN         115000.0            45.98
5          NaN         115000.0            45.98
6          NaN         115000.0            45.98
7          NaN         115000.0            45.98
8          NaN         115000.0            45.98
9          NaN         115000.0            45.98
10         NaN         115000.0            45.98

In [18]:
df_unique = df_filled

In [24]:
df_unique = df_unique.drop_duplicates(subset=['job_title', 'company_name'])

In [25]:
len(df_unique)

508042

In [26]:
len(df_filled)

785741

In [27]:
df_unique

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,115000.0,45.98,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,115000.0,45.98,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,115000.0,45.98,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,115000.0,45.98,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,115000.0,45.98,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785735,Senior Data Engineer,Senior Data Engineer,"Berlin, Jerman",melalui Top County Careers,Pekerjaan tetap,False,Germany,2023-03-13 06:19:07,False,False,Germany,NaN,115000.0,45.98,Pure App,"['sql', 'python', 'bigquery', 'aws', 'airflow'...","{'cloud': ['bigquery', 'aws'], 'libraries': ['..."
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,115000.0,45.98,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,115000.0,45.98,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,115000.0,45.98,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,115000.0,45.98,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

Data Management

In [28]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,115000.0,45.98,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,115000.0,45.98,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,115000.0,45.98,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,115000.0,45.98,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,115000.0,45.98,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,115000.0,45.98,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,115000.0,45.98,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,115000.0,45.98,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,115000.0,45.98,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,115000.0,45.98,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [29]:
df.sample(20, random_state=42) #allows us to return the same result everytime instead of random

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
60067,Data Engineer,Data Engineering Manager,"Cannon Hill QLD, Australia",via Trabajo.org,Full-time,False,Australia,2023-11-02 06:15:44,True,False,Australia,NaN,115000.0,45.98,Endeavour Foundation,"['sql', 'azure', 'databricks', 'bigquery', 'sn...","{'analyst_tools': ['power bi'], 'cloud': ['azu..."
476140,Data Analyst,Remote Language Data Analyst - English (UK mar...,Venezuela,via Jobenka.Com,Full-time,False,Venezuela,2023-04-17 14:29:19,True,False,Venezuela,NaN,115000.0,45.98,TransPerfect,['react'],{'libraries': ['react']}
525659,Data Engineer,Data Engineer,"Copenhagen, Denmark",via LinkedIn,Full-time,False,Denmark,2023-07-08 11:23:38,False,False,Denmark,NaN,115000.0,45.98,Workday,"['python', 'java', 'sql', 'nosql', 'aws', 'gcp...","{'analyst_tools': ['tableau'], 'cloud': ['aws'..."
299496,Data Engineer,Lead Data Engineer Job in Capital One Salisbur...,"Salisbury, MD",via Sulekha Jobs,Full-time,False,"Florida, United States",2023-02-01 17:50:10,True,False,United States,NaN,115000.0,45.98,Capital One,NaN,NaN
229632,Data Analyst,Data Analyst/Power BI Reporting,India,via Indeed,Full-time,False,India,2023-07-10 07:32:32,True,False,India,NaN,115000.0,45.98,Simplex Services,"['sql', 'sql server', 'power bi', 'tableau', '...","{'analyst_tools': ['power bi', 'tableau', 'sap..."
306617,Data Engineer,Data Engineer / Data Analyst Performance Analy...,"West Bromwich, UK",via WREG Jobs,Full-time,False,United Kingdom,2023-06-16 17:51:30,True,False,United Kingdom,NaN,115000.0,45.98,Deutsche Bank,NaN,NaN
438824,Data Engineer,Junior Data Engineer,"Zürich, Switzerland",via BeBee Schweiz,Full-time,False,Switzerland,2023-05-11 16:36:30,True,False,Switzerland,NaN,115000.0,45.98,pmOne Schweiz GmbH,"['python', 'azure', 'databricks', 'spark']","{'cloud': ['azure', 'databricks'], 'libraries'..."
260038,Data Analyst,Data Analyst,Belgium,via BeBee Belgique,Temp work,False,Belgium,2023-12-08 07:39:24,False,False,Belgium,NaN,115000.0,45.98,Unique,"['excel', 'power bi', 'cognos']","{'analyst_tools': ['excel', 'power bi', 'cogno..."
668388,Business Analyst,Analyst,"Rome, Metropolitan City of Rome Capital, Italy",via BeBee,Full-time,False,Italy,2023-11-26 10:38:57,False,False,Italy,NaN,115000.0,45.98,Hunters Group,NaN,NaN
592187,Data Engineer,Senior Data Engineer Vacature,"Nederland, Netherlands",via BeBee,Full-time,False,Netherlands,2023-11-07 09:46:36,False,False,Netherlands,NaN,115000.0,45.98,Insulet Corporation,"['sql', 'python', 'java', 'c', 'azure', 'bigqu...","{'cloud': ['azure', 'bigquery', 'aws'], 'libra..."
578919,Data Engineer,Data Engineer - stage ou alternance,"Boulogne-Billancourt, France",via Welcome To The Jungle,Internship,False,France,2023-05-04 09:21:30,False,False,France,NaN,115000.0,45.98,Eskimoz,"['python', 'bigquery', 'gcp', 'pandas', 'github']","{'cloud': ['bigquery', 'gcp'], 'libraries': ['..."
117742,Business Analyst,Operations Analyst,"Heredia Province, Heredia, Costa Rica",via Trabajo.org,Full-time,False,Costa Rica,2023-01-12 09:12:29,False,False,Costa Rica,NaN,115000.0,45.98,Vigeo Eiris,"['vba', 'excel', 'powerpoint']","{'analyst_tools': ['excel', 'powerpoint'], 'pr..."
74496,Data Engineer,Lead Cloud Data Engineer,"Westlake Village, CA",via The Muse,Full-time,False,"Illinois, United States",2023-07-16 00:07:12,True,True,United States,NaN,115000.0,45.98,Kforce,"['java', 'aws', 'redshift', 'airflow', 'spark'...","{'analyst_tools': ['tableau'], 'cloud': ['aws'..."
82543,Business Analyst,Senior Business Development Manager,"Bangkok, Thailand",via Recruit.net,Full-time,False,Thailand,2023-08-18 00:22:40,False,False,Thailand,NaN,115000.0,45.98,Sertis,"['word', 'spreadsheet']","{'analyst_tools': ['word', 'spreadsheet']}"
470189,Data Scientist,Data Scientist Lead,"Jakarta, Indonesia",via LinkedIn,Full-time,False,Indonesia,2023-10-17 14:21:45,False,False,Indonesia,NaN,115000.0,45.98,DANA Indonesia,"['python', 'r', 'sas', 'sas', 'ssrs', 'tableau']","{'analyst_tools': ['sas', 'ssrs', 'tableau'], ..."
686288,Data Analyst,Data Analyst - Research Specialist - Center fo...,"Chicago, IL",via ZipRecruiter,Full-time,False,"Illinois, United States",2023-07-14 10:02:03,True,False,United States,NaN,115000.0,45.98,Shirley Ryan AbilityLab,NaN,NaN
723545,Data Engineer,Data Engineer H/F,"Villeneuve-d'Ascq, France",via Jobijoba,Full-time,False,France,2023-06-23 22:03:05,False,False,France,NaN,115000.0,45.98,Clinitex,"['vmware', 'chef']","{'cloud': ['vmware'], 'other': ['chef']}"
510600,Data Analyst,Data Analyst,Romania,via LinkedIn,Full-time,False,Romania,2023-07-14 11:26:32,False,False,Romania,NaN,115000.0,45.98,Vitesco Technologies,"['html', 'javascript', 'css', 'python', 'bash'...","{'analyst_tools': ['sap'], 'cloud': ['aws', 'a..."
400193,Senior Data Analyst,Senior Data Analyst,Hong Kong,via BeBee 香港,Full-time,False,Hong Kong,2023-05-28 18:10:40,False,False,Hong Kong,NaN,115000.0,45.98,ELEVATE Hong Kong Holdings Limited,"['python', 'sql', 'tableau', 'excel']","{'analyst_tools': ['tableau', 'excel'], 'progr..."
30104,Data Scientist,"Scientist, Data (Consumer & High Net Worth Cli...","Windhoek, Namibia",via SmartRecruiters Job Search,Full-time,False,Namibia,2023-01-04 14:04:06,True,False,Namibia,NaN,115000.0,45.98,Standard Bank Group,"['sas', 'sas', 'r', 'spss', 'power bi', 'table...","{'analyst_tools': ['sas', 'spss', 'power bi', ..."

df.copy() method allows us to maintain the data in our original data frame as we create and make modifications to different versions of it