Cleaning

In [3]:
import pandas as pd
from datasets import load_dataset

# Loading data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

In [4]:
type(df.job_posted_date[80])

str

In [5]:
pd.to_datetime(df.job_posted_date)

0        2023-06-16 13:44:15
1        2023-01-14 13:18:07
2        2023-10-10 13:14:55
3        2023-07-04 13:01:41
4        2023-08-07 14:29:36
                 ...
785736   2023-03-13 06:16:16
785737   2023-03-12 06:18:18
785738   2023-03-12 06:32:36
785739   2023-03-12 06:32:15
785740   2023-03-13 06:16:31
Name: job_posted_date, Length: 785741, dtype: datetime64[us]

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  str
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), float64(2), str(12)
memory usage: 279.3 MB

In [7]:
df.job_posted_date = pd.to_datetime(df.job_posted_date)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB

In [9]:
df.job_posted_date.dt.month

0          6
1          1
2         10
3          7
4          8
          ..
785736     3
785737     3
785738     3
785739     3
785740     3
Name: job_posted_date, Length: 785741, dtype: int32

In [10]:
df['job_posted_month'] = df.job_posted_date.dt.month
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
 17  job_posted_month       785741 non-null  int32
dtypes: bool(3), datetime64[us](1), float64(2), int32(1), str(11)
memory usage: 268.1 MB

In [11]:
df.job_posted_month

0          6
1          1
2         10
3          7
4          8
          ..
785736     3
785737     3
785738     3
785739     3
785740     3
Name: job_posted_month, Length: 785741, dtype: int32

In [12]:
df.sort_values(by=['job_posted_month'], inplace=True)

In [13]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
335487,Data Scientist,Data Modeler,"San Francisco, CA",via LinkedIn,Contractor,False,"California, United States",2023-01-01 23:01:35,True,False,United States,NaN,NaN,NaN,Micasa Global,"['sql', 'javascript', 'python', 'sas', 'sas', ...","{'analyst_tools': ['sas', 'excel', 'spss'], 'c...",1
335486,Software Engineer,Principal Software Engineer,"Edmonton, AB, Canada",via Simplify Jobs,Full-time,False,Canada,2023-01-02 23:30:22,True,False,Canada,NaN,NaN,NaN,Clari,"['java', 'mongodb', 'mongodb', 'aws', 'aurora'...","{'cloud': ['aws', 'aurora'], 'databases': ['mo...",1
335485,Data Engineer,Es- Data Engineer Azure,"Madrid, Spain",via Recruit.net,Full-time,False,Spain,2023-01-10 23:41:18,True,False,Spain,NaN,NaN,NaN,Devoteam,"['aws', 'databricks', 'snowflake', 'alteryx', ...","{'analyst_tools': ['alteryx', 'tableau', 'qlik...",1
39,Data Engineer,Data Engineer,"Fort Worth, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01-25 13:24:01,False,False,United States,NaN,NaN,NaN,Programmers.io,"['sql', 'python']","{'programming': ['sql', 'python']}",1
472238,Data Scientist,Data Scientist,"Birmingham, AL","via Birmingham, AL - Geebo",Full-time,False,"Florida, United States",2023-01-03 23:35:29,False,True,United States,hour,NaN,24.0,Protective,"['r', 'python', 'sas', 'sas', 'sql', 'databric...","{'analyst_tools': ['sas', 'powerpoint'], 'clou...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309117,Data Scientist,Data Scientist,United States,via LinkedIn,Full-time,False,"Texas, United States",2023-12-01 17:02:45,False,False,United States,NaN,NaN,NaN,Core Digital Media,"['python', 'sql', 'r', 'sas', 'sas', 'scikit-l...","{'analyst_tools': ['sas', 'power bi'], 'librar...",12
363983,Data Analyst,Luxury Retail - Regional Data Insight Consulta...,Hong Kong,via Recruit.net,Contractor,False,Hong Kong,2023-12-15 23:37:03,True,False,Hong Kong,NaN,NaN,NaN,Ambition Group Hong Kong Limited,"['sql', 'r', 'python', 'power bi']","{'analyst_tools': ['power bi'], 'programming':...",12
139582,Data Engineer,Data Engineer,Morocco,via LinkedIn,Full-time,False,Morocco,2023-12-13 08:22:10,False,False,Morocco,NaN,NaN,NaN,Groupe Managem,"['nosql', 'sql', 'python', 'r', 'javascript', ...","{'cloud': ['azure'], 'libraries': ['hadoop'], ...",12
139580,Data Scientist,Data Scientist,"Bengaluru, Karnataka, India",via BeBee India,Full-time,False,India,2023-12-06 08:08:51,False,False,India,NaN,NaN,NaN,NMS Consultant,"['r', 'scala', 'python', 'matlab']","{'programming': ['r', 'scala', 'python', 'matl...",12
335504,Data Analyst,Data Analysis,Thailand,via หางาน | Indeed,Full-time,False,Thailand,2023-12-05 23:22:15,False,False,Thailand,NaN,NaN,NaN,บริษัท คุ้มสึ จำกัด,"['sql', 'python', 'r', 'vba', 'matlab', 'power...","{'analyst_tools': ['power bi', 'excel', 'ms ac...",12

In [14]:
df.drop(labels='salary_hour_avg', axis=1, inplace=True)

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 785741 entries, 335487 to 335504
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  company_name           785723 non-null  str
 14  job_skills             668704 non-null  str
 15  job_type_skills        668704 non-null  str
 16  job_posted_month       785741 non-null  int32
dtypes: bool(3), datetime64[us](1), float64(1), int32(1), str(11)
memory usage: 268.7 MB

In [17]:
df.dropna(subset=['salary_year_avg'], inplace=True)

In [18]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,company_name,job_skills,job_type_skills,job_posted_month
335447,Data Analyst,Electronic Data Interchange Analyst,Anywhere,via LinkedIn,Full-time,True,"Texas, United States",2023-01-18 23:02:57,True,True,United States,year,65000.0,Insight Global,['excel'],{'analyst_tools': ['excel']},1
785641,Data Engineer,Data Engineer,"New York, NY",via Dice,Full-time,False,Georgia,2023-01-04 16:36:07,True,False,United States,year,150000.0,"Engage Partners, Inc.",NaN,NaN,1
156398,Data Scientist,Principal / Sr. Principal Data Scientist,"Clearfield, UT",via Ladders,Full-time,False,"California, United States",2023-01-19 08:21:50,False,True,United States,year,90000.0,Northrop Grumman,['sap'],{'analyst_tools': ['sap']},1
785563,Data Scientist,Data Scientist I/II (Model Risk Management & M...,"Pensacola, FL",via Navy Federal Credit Union - Talentify,Full-time,False,"Florida, United States",2023-01-11 06:22:10,False,False,United States,year,136400.0,Navy Federal Credit Union,"['r', 'python', 'matplotlib', 'ggplot2', 'spar...","{'analyst_tools': ['word', 'power bi', 'tablea...",1
575522,Data Scientist,Scientist (Computational Nuclear Data Scientist),"Los Alamos, NM",via Ladders,Full-time,False,Sudan,2023-01-31 10:34:22,False,True,Sudan,year,115000.0,Los Alamos National Laboratory,"['c++', 'python']","{'programming': ['c++', 'python']}",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527097,Software Engineer,BI Developer,"Jakarta, Indonesia",via Ai-Jobs.net,Full-time,False,Indonesia,2023-12-19 11:39:07,False,False,Indonesia,year,123000.0,NTT DATA,"['java', 'python', 'sql', 'no-sql', 'mongodb',...","{'analyst_tools': ['ssis', 'ssrs', 'tableau'],...",12
785395,Data Engineer,Senior Consultant - Tech Consulting -Azure Dat...,India,via Ai-Jobs.net,Full-time,False,India,2023-12-19 06:10:41,False,False,India,year,64800.0,EY,"['sql', 'python', 'azure', 'databricks', 'spar...","{'analyst_tools': ['power bi', 'tableau', 'qli...",12
139434,Data Analyst,Management & Program Analyst (Data Analyst),"Arlington, VA",via ZipRecruiter,Full-time,False,"New York, United States",2023-12-27 08:00:18,True,False,United States,year,156000.0,Office of the Secretary of Defense,"['c', 'terminal']","{'other': ['terminal'], 'programming': ['c']}",12
665161,Senior Data Scientist,Senior Credit Strategy Analyst/ Senior Data Sc...,"Frisco, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-12-29 10:02:21,False,True,United States,year,170000.0,SoFi,"['sql', 'python', 'excel', 'tableau']","{'analyst_tools': ['excel', 'tableau'], 'progr...",12
527579,Data Analyst,Data Analyst,"Elk Grove Village, IL",via BeBee,Full-time,False,"Illinois, United States",2023-12-13 11:02:27,False,False,United States,year,65000.0,First American Bank,NaN,NaN,12

In [23]:
df[df.salary_year_avg == 'NAN']['salary_year_avg']

Series([], Name: salary_year_avg, dtype: float64)

In [24]:
df.info()

<class 'pandas.DataFrame'>
Index: 22003 entries, 335447 to 527579
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        22003 non-null  str
 1   job_title              22003 non-null  str
 2   job_location           21723 non-null  str
 3   job_via                22003 non-null  str
 4   job_schedule_type      21987 non-null  str
 5   job_work_from_home     22003 non-null  bool
 6   search_location        22003 non-null  str
 7   job_posted_date        22003 non-null  datetime64[us]
 8   job_no_degree_mention  22003 non-null  bool
 9   job_health_insurance   22003 non-null  bool
 10  job_country            22003 non-null  str
 11  salary_rate            22003 non-null  str
 12  salary_year_avg        22003 non-null  float64
 13  company_name           22003 non-null  str
 14  job_skills             20170 non-null  str
 15  job_type_skills        20170 non-null  str
 16  job_posted_month       22003 non-null  int32
dtypes: bool(3), datetime64[us](1), float64(1), int32(1), str(11)
memory usage: 8.1 MB